apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agromart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ashuj56/Agromart # ← replace with your GitHub URL
    targetRevision: main
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: agromart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true