apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: agromart
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: agromart-backend-sa   # IRSA service account — created by Terraform
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agromart-backend-secrets
  namespace: agromart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: agromart-backend-secrets      # creates this K8s Secret automatically
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: agromart/backend           # name of secret in AWS Secrets Manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agromart-frontend-secrets
  namespace: agromart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: agromart-frontend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: agromart/frontend          # name of secret in AWS Secrets Manager
