apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: agromart
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migrate
          # CI will update this tag on every deploy (same image as backend)
          image: 848647692924.dkr.ecr.us-east-1.amazonaws.com/agromart-backend:e2f62ced43ff73fde3710912a5ec402ebb0501f1
          command: ["node", "node_modules/prisma/build/index.js", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: agromart-backend-secrets   # provides DATABASE_URL
