apiVersion: v1
kind: Secret
metadata:
  name: agromart-backend-secrets
  namespace: agromart
type: Opaque
stringData:
  DATABASE_URL: "postgresql://agromart_admin:YourDbPassword@<rds-endpoint>:5432/agromart?schema=public"
  REDIS_URL: "redis://<redis-endpoint>:6379"
  JWT_SECRET: "your-jwt-secret-key-at-least-32-chars"
  RAZORPAY_KEY_ID: "rzp_test_xxxxxx"
  RAZORPAY_KEY_SECRET: "your_razorpay_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: agromart-frontend-secrets
  namespace: agromart
type: Opaque
stringData:
  NEXT_PUBLIC_RAZORPAY_KEY_ID: "rzp_test_xxxxxx"