apiVersion: v1
kind: ServiceAccount
metadata:
  name: agromart-backend-sa
  namespace: agromart
  annotations:
    # Replace <account_id> with your AWS account ID after running:
    # terraform output backend_sa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/agromart-backend-sa-role
